/**
 * Executes an array of function generating promises in series.
 *
 * @param {array} promiseFns An array of promise generating functions
 *
 * @returns {Promise} A promise that resolves after all promises generated by
 *                    by the array have resolved
 */
export default function pseries(promiseFns) {
  if (promiseFns.length < 1) { return Promise.resolve(); }

  const [first, ...rest] = promiseFns;

  if (rest && rest.length > 0) {
    return rest.reduce((pacc, fn) => pacc.then(fn), first());
  }

  return first();
}
