/**
 * Executes an array of function generating promises in series.
 *
 * @param {array} promiseFns An array of promise generating functions
 *
 * @returns {Promise} A promise that resolves after all promises generated by
 *                    by the array have resolved
 */
export default function pseries(promiseFns) {
  if (promiseFns.length < 1) { return Promise.resolve(); }

  const [first, ...rest] = promiseFns;

  if (rest && rest.length > 0) {
    return rest.reduce(
      (pacc, next) => {
        const pm = pacc && pacc.then ? pacc : Promise.resolve();
        return pm.then(next);
      },
      first()
    );
  }

  return first();
}
